### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by RinRax** [adoptium/adoptium-support#1013]
### Please provide a brief summary of the bug

The Game always Crashes when I open an ender chest, no matter if its on a server or just in a singleplayer world, and it also crashes when i try to play my redstone testworld. it say "saving world" for a split second, but then it crashes completely. it says "error during messaging worker: An existing connection was forcibly closed by the remote host. (os error 10054)"

### Did you test with the latest update version?

```Shell
yes, i have the latest version
```

### Please provide steps to reproduce where possible

start the game, go into any world, open an ender chest

### Expected Results

i expect to be able to play the game

### Actual Results

it crashes

### What Java Version are you using?

1.20.4

### What is your operating system and platform?

Windows 11

### How did you install Java?

through the official launcher, i bought it

### Did it work before?

```Shell
it stopped working today, even though i changed nothing. i played, went away for an hour and then it started crashing
```

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are reporting that the game Minecraft crashed for you. Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact our team to address the issue.
