### ISSUE TITLE
incompatible resolution on feather client

### ISSUE THREAD

**Issue by arch962** [adoptium/adoptium-support#1055]
### Please provide a brief summary of the bug

i changed my resolution to an incompatible one for my monitor on feather client then it kicked me of the game now i cannot launch 1.20.4. i do not know what to do please help resolve my issue.

### Did you test with the latest update version?

- [ ] Yes

### Please provide steps to reproduce where possible

yes

### Expected Results

my resolution would change then i would change it straight back to normal. i tried to get an fps boost thats why i changed resolution

### Actual Results

i couldnt load back on

### What Java Version are you using?

java 1.20.4

### What is your operating system and platform?

window 10

### How did you install Java?

launcher

### Did it work before?

```Shell
yes
```

### Did you test with other Java versions?

```Shell
yes
```

### Relevant log output

```Shell
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe67bf5ba0, pid=11216, tid=12708
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.3+7 (17.0.3+7) (build 17.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (17.0.3+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C
info: [glfw.dll+0x5ba0]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
info: # An error report file with more information is saved as:
# feather/java_error.log
info: #
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
info: [2024-04-10T00:43:56Z ERROR rust_launcher::messaging::channel] error during messaging worker: An existing connection was forcibly closed by the remote host. (os error 10054)
    
    Stack backtrace:
       0: napi_register_module_v1
       1: napi_register_module_v1
       2: bz_internal_error
       3: napi_register_module_v1
       4: napi_register_module_v1
       5: napi_register_module_v1
       6: napi_register_module_v1
       7: napi_register_module_v1
       8: napi_register_module_v1
       9: BaseThreadInitThunk
      10: RtlUserThreadStart
info: [2024-04-10T00:43:56Z INFO  rust_launcher::start::bindings] launch stalled
```

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are reporting that the game Minecraft crashed for you. Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact our team to address the issue.
