### ISSUE TITLE
Is there any permanent link to download Eclipse Temurin?

### ISSUE THREAD

**Issue by TEST173209** [adoptium/adoptium-support#1056]
## Question

Is there any way to get a permanent link to download Eclipse Temurin?
If not, could it be a feature under consideration.

## Context

Some dists (such as Oracle, Microsoft, etc) provide permanent links to download jdksCould Temurin provide this feature as well.

For Example, to download jdk8, URL  `https://adoptium.net/zh-CN/download/8/JDK_8_windows_x64_latest.msi`(I made this up) always get the latest version of jdk8 installer for Windows x64, similiar to other platform/architecture and the checksum.

It would be very nice for automatic tools and sync platfrom if it is available.

Regardings

Java version: Not specified

Your operating system and platform: Not specified

**Comment by sxa** [comment]
We do already provide the API at api.adoptium.net which allows you to get a redirect to the latest download. For example: https://api.adoptium.net/v3/binary/latest/8/ga/windows/x64/jdk/hotspot/normal/adoptium is (almost) the link you're looking for. I say almost because that's the zip file, not the MSI installer. Is that adequate for your needs?

It is possible to locate the MSI installer but it's a bit more work, for example you can retrieve the JSON from:
https://api.adoptium.net/v3/assets/feature_releases/8/ga?architecture=x64&image_type=jdk&jvm_impl=hotspot&os=windows&page=0&page_size=1&project=jdk&vendor=eclipse and find the binaries/installer/link in there get the underlying URL to the MSI. It's not ideal, but gives you an option for now if you need to automatically download and [install](https://adoptium.net/en-GB/installation/windows/) the MSI file

I would also suggest raising a feature request at https://github.com/adoptium/api.adoptium.net/issues/new/choose to make the installers more easily accessible in a single API call in the same way as the zip ones, as I hadn't realised we didn't already have that funtionality and it would be a good addition.

**References:**
- [API "Swagger" UI for generating and testing api calls](https://api.adoptium.net/swagger-ui)
- [Some API examples for pulling "early access" builds](https://adoptium.net/en-GB/blog/2024/02/early-access-builds-feb2024/). While that post is about ea builds, in general the GA (release) versions can be obtained by replacing "ea" with "ga" in the API links

Hope that helps!
