### ISSUE TITLE
Crash pc=0x00007ffac21cf4c5, pid=16784, tid=0x0000000000002fac      hs_err_pid16784.log

### ISSUE THREAD

**Issue by kazek1009** [adoptium/adoptium-support#1092]
### Please provide a brief summary of the bug

A fatal error has been detected by the Java Runtime Environment:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffac21cf4c5, pid=16784, tid=0x0000000000002fac

JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode windows-amd64 compressed oops)
Problematic frame:
C  [atio6axx.dll+0x1f6f4c5]

Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:
 C:\Users\kamil\AppData\Local\Temp\\hs_err_pid16784.log

### Did you test with the latest update version?

- [ ] Yes

### Expected Results

crash

### Actual Results

crash

### What Java Version are you using?

1.16

**Comment by kazek1009** [comment]
crash after opening inventory

**Comment by karianna** [comment]
Please try with latest 1.8.0_412 - which game is this?

**Comment by kazek1009** [comment]
FTB OceanBlock 1.16

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are using a modified version of Minecraft. The following was detected in your crash report:
```
--launchTarget forgeclient
--fml.forgeVersion
```
Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- Try disabling the mods you have installed one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact us to address the issue.
