### ISSUE TITLE
ftb builders paradise 2 crashes on new instance (ftb app)

### ISSUE THREAD

**Issue by a-masterchief69** [adoptium/adoptium-support#1119]
### Please provide a brief summary of the bug

very first time ever installing this pack it crashed immediately on startup with no modifications, reinstalled several times and restarted device with no change

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

open ftb app, select builders paradise 2, install, open - it crashes

### Expected Results

load instance of game

### Actual Results

instant crash with no immediate reason i can see.
here is file with log of crash as the form refuses to allow me to paste it as instructed due to length of log
[hs_err_pid9744.log](https://github.com/user-attachments/files/15951399/hs_err_pid9744.log)

### What Java Version are you using?

java 22.0.1 2024-04-16 Java(TM) SE Runtime Environment (build 22.0.1+8-16) Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

### What is your operating system and platform?

AMD Ryzen 5 5500U with Radeon Graphics , 12 cores, 31G,  Windows 11 , 64 bit Build 22621

### How did you install Java?

site:
https://www.oracle.com/java/technologies/downloads/#jdk22-windows
actual install link:
https://download.oracle.com/java/22/latest/jdk-22_windows-x64_bin.zip.sha256

### Did it work before?

```Shell
ftb builders paradise 2 has not worked before as i have not used it prior, all other modpacks used have worked including: stoneblock 3, stoneblock 2, skyfactory 4
```

### Did you test with other Java versions?

```Shell
only tested with the one version which is supposed to be the latest release:
java 22.0.1 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)
```

### Relevant log output

```Shell
cannot add here due to your form not allowing it:
"There was an error creating your issue: body is too long (maximum is 65536 characters)"

i will attach as a file instead.
```

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are reporting that the game Minecraft crashed for you. Please try the following:
- Update your graphics drivers, see [this Minecraft aHelp Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact our team to address the issue.
