### ISSUE TITLE
Kinaxis launches then immediately crashes

### ISSUE THREAD

**Issue by DaveM1989** [adoptium/adoptium-support#1120]
### Please provide a brief summary of the bug

Hello everyone, 

We are using Temurin to run Kinaxis, we recently changed from Oracle Java to Temurin,  and we started getting this issue. 
We checked all the settings and clean all the cache files. 

Windows Defender is not blocking the application as there are no events created for this in event viewer. 

When we launch the session this is what we get in the event viewer. 

![image](https://github.com/adoptium/adoptium-support/assets/173810280/8049fa6e-133d-456f-b574-3fea69230e31)
![image](https://github.com/adoptium/adoptium-support/assets/173810280/e656e051-0adb-449e-82b4-02065d705e84)

### Did you test with the latest update version?

- [X] Yes

### Expected Results

Kinaxis should launch and able to use the application. 

### Actual Results

Kinaxis crashes as soon as is launched. 

### What Java Version are you using?

jdk8u412-b08

### What is your operating system and platform?

Windows 11 23h2 x64

### How did you install Java?

MSI

### Did it work before?

```Shell
Yes
```

### Did you test with other Java versions?

```Shell
Yes, we tried Java oracle, Kinaxis mentions that the latest Temurin version should work.
```

**Comment by karianna** [comment]
@DaveM1989 There's not enough info to debug further here. It _looks_ like an interaction with libcef.dll is causing the crash.  This typically happens when the Java app calls out to a native component (in this case the Chromium Embedded Framework.

I'd recommend talking to Kinaxis and see if they can suggest extra debug logs or similar to look at.

-----

From GPT4o

`libcef.dll` is a dynamic link library (DLL) associated with the Chromium Embedded Framework (CEF). The CEF is an open-source project that allows developers to embed the Chromium web browser within their applications. `libcef.dll` provides the core functionality for rendering web content and handling web-related tasks in applications that use CEF.

### Key Points about `libcef.dll`:

1. **Web Rendering**: It enables applications to render HTML, CSS, and JavaScript content using the Chromium engine, similar to how Google Chrome renders web pages.

2. **Cross-Platform**: CEF is designed to be cross-platform, meaning `libcef.dll` can be used on different operating systems, including Windows, macOS, and Linux.

3. **Embedding**: Applications that require web content to be displayed or interacted with, such as game launchers, software with built-in web browsers, or other tools with web-based user interfaces, often use `libcef.dll`.

4. **Dependencies**: Applications using CEF need `libcef.dll` to function correctly. If this DLL is missing or corrupted, the application may fail to run or display web content properly.

### Common Issues and Troubleshooting:

- **Missing or Not Found**: If an application complains about a missing `libcef.dll`, reinstalling the application or downloading the required DLL file from a trusted source may resolve the issue.
- **Corruption**: Corrupted `libcef.dll` files can cause crashes or malfunctioning applications. Running system checks or reinstalling the affected application can help.
- **Compatibility**: Ensuring that the version of `libcef.dll` matches the version expected by the application is important for compatibility.

If you encounter specific issues with `libcef.dll`, providing more details about the error or context can help in diagnosing the problem further.
