### ISSUE TITLE
JDK 21: java.text.ParseException: Unparseable date: "Jun 3, 2024, 8:11:02 AM"

### ISSUE THREAD

**Issue by lawrencejacoby** [adoptium/adoptium-support#1124]
### Please provide a brief summary of the bug

with jdk 17 the following works:
```
		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.MEDIUM, DateFormat.MEDIUM,Locale.US);
		System.out.println(dateFormat.parse("Jun 3, 2024, 8:11:02 AM"));
```
with jdk 21 i get the exception.

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.MEDIUM, DateFormat.MEDIUM,Locale.US);
		System.out.println(dateFormat.parse("Jun 3, 2024, 8:11:02 AM"));

### Expected Results

code parses the string like  jdk 17

### Actual Results

code throws java.text.ParseException: Unparseable date: "Jun 3, 2024, 8:11:02 AM"

### What Java Version are you using?

openjdk version "21.0.3" 2024-04-16 LTS

### What is your operating system and platform?

Ubuntu 22.04.4 LTS  x64

**Comment by jerboaa** [comment]
This is a known issue caused by the [CLDR update to version 42 ](https://bugs.openjdk.org/browse/JDK-8284840) in JDK 20 (which is included in JDK 21). See for example this bug for an analysis: https://bugs.openjdk.org/browse/JDK-8304925

The issue is for the text to become parsable it would need to replace ascii space with `NBSP` or `NNBSP` before `AM` before parsing.
