### ISSUE TITLE
 EXCEPTION_ACCESS_VIOLATION error using shaders

### ISSUE THREAD

**Issue by Monke567** [adoptium/adoptium-support#1142]
### Please provide a brief summary of the bug

This came up along with "EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff907a733b0, pid=11540, tid=15280"
when i was using chocapic13_HighPerformance_Toaster.zip shaders, and it let me in the overworld, but when i tried to go in nether, it crashed with exit code 1. The problematic frame was "ig7icd64.dll+0x4533b0".

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

There is an exit code: 1, and it says it is in the "ig7icd64.dll" file. 

### Expected Results

I wanted to use the shader pack in the nether. 

### Actual Results

It crashed with exit code:1.

### What Java Version are you using?

JDK-22

### What is your operating system and platform?

Windows 10 x64 bit

### How did you install Java?

I used java.com download

### Did it work before?

```Shell
no
```

### Did you test with other Java versions?

```Shell
I tested JDK-8
```

### Relevant log output

```Shell
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff907a733b0, pid=11540, tid=15280
#
# JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8+7) (build 17.0.8+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [ig7icd64.dll+0x4533b0]
```

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are reporting that the game Minecraft crashed for you. Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact our team to address the issue.
