### ISSUE TITLE
DOM parsing does not preserve the document's encoding

### ISSUE THREAD

**Issue by dirk-olmes** [adoptium/adoptium-support#1170]
### Please provide a brief summary of the bug

DOM-parsing an XML file with an encoding specified in the XML preamble seems to change the internal encoding to UTF-8. The original Xerces preserved the encoding.

### Did you test with the latest update version?

- [X] Yes

### Please provide steps to reproduce where possible

Minimal reproducer with more details can be found here: https://github.com/comlinegmbh/xerxes-vs-jdk-encoding-error-poc

### Expected Results

org.w3c.dom.Document.getInputEncoding() should be the same as the encoding specified in the XML file's preamble

### Actual Results

org.w3c.dom.Document.getInputEncoding() is converted to UTF-8

### What Java Version are you using?

$ java --version openjdk 21.0.4 2024-07-16 LTS OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)

### What is your operating system and platform?

Betriebssystemname:                            Microsoft Windows 11 Enterprise
Betriebssystemversion:                         10.0.22621 Nicht zutreffend Build 22621

### How did you install Java?

Zip downloaded from adoptium.net

**Comment by hhoffstaette** [comment]
Reproduced on Linux with JDK-22 (Temurin-22.0.2+9 (build 22.0.2+9)).

**Comment by jerboaa** [comment]
@dirk-olmes Are you sure you don't want `getXmlEncoding()`?
https://docs.oracle.com/en/java/javase/21/docs/api/java.xml/org/w3c/dom/Document.html#getXmlEncoding()

```
diff --git a/src/test/java/de/comline/XercesTest.java b/src/test/java/de/comline/XercesTest.java
index da37ca6..03d23e8 100644
--- a/src/test/java/de/comline/XercesTest.java
+++ b/src/test/java/de/comline/XercesTest.java
@@ -22,7 +22,8 @@ class XercesTest {
 
         try (InputStream input = getClass().getClassLoader().getResourceAsStream("iso-8859-15.xml")) {
             Document document = builder.parse(input);
-            assertEquals("ISO-8859-15", document.getInputEncoding());
+            //assertEquals("ISO-8859-15", document.getInputEncoding());
+            assertEquals("ISO-8859-15", document.getXmlEncoding());
         }
     }
 }
```

`getInputEncoding()` javadoc has:
https://docs.oracle.com/en/java/javase/21/docs/api/java.xml/org/w3c/dom/Document.html#getInputEncoding()
```
An attribute specifying the encoding used for this document at the time of the parsing. This is null when it is not known, such as when the Document was created in memory.
```

**Comment by hhoffstaette** [comment]
> @dirk-olmes Are you sure you don't want `getXmlEncoding()`?

Hello Severin,
thanks for taking a look. I'm not Dirk (just trying to help) but have been trying to debug this for the last few hours, and there is **definitely** an inconsistency between the JDK and external implementations
.
So far what I've found is that the external xerces calls `org.apache.xerces.dom.CoreDocumentImpl.setInputEncoding(String)` twice: once from `org.apache.xerces.parsers.AbstractDOMParser.startDocument(XMLLocator, String, NamespaceContext, Augmentations)` and once from `org.apache.xerces.parsers.AbstractDOMParser.endDocument(Augmentations)`. The first time it sets the encoding to UTF-8, the second time it passes the encoding from the document.

This second pass does **not** happen with the JDK-internal implementation.
There are several slight differences in the code bases and unfortunately it is insanely difficult to find what goes wrong where since the external xerces-2.12.2 has been built without line number information. :(

**Comment by jerboaa** [comment]
> Expected Results
>
> org.w3c.dom.Document.getInputEncoding() should be the same as the encoding specified in the XML file's preamble

I'm questioning this expectation.

The file of the reproducer is in ISO-8859 encoding. The parser retrieves text nodes correctly converted from that encoding. A problem arises if the file would be encoded in, say, `UTF-8`, yet the XML `encoding` attribute claiming it being `ISO-8859-15`.

**Comment by dirk-olmes** [comment]
@jerboaa reading the javadocs for getInputEncoding() and getXmlEncoding() I'm not sure why you question the expectation? 

getInputEncoding() should, per javadoc, return the encoding used at parsing time. Since the file is saved in ISO-8859-15 why would getInputEncoding return a wrong value?

I changed our codebase to use getXmlEncoding and all tests run green. So the general behaviour seems to be OK.

**Comment by jerboaa** [comment]
> @jerboaa reading the javadocs for getInputEncoding() and getXmlEncoding() I'm not sure why you question the expectation?
> 
> getInputEncoding() should, per javadoc, return the encoding used at parsing time. Since the file is saved in ISO-8859-15 why would getInputEncoding return a wrong value?

`getInputEncoding()` is the encoding used when reading the first few bytes of the byte stream (in your case the byte stream from the xml file retrieved via `getClass().getClassLoader().getResourceAsStream()`; that API has no notion of the stream being an XML file). This will be generally UTF-8. Basically it's reading the `<?xml ...` tokens of the first line (if any). Only later will the actual declared character encoding be used for translating character (text) data. I.e. the two are different, because you need to read in some data first to know the declared encoding. Note, that unless declared otherwise, like in your example, the encoding is assumed to be UTF-8. Classic chicken-and-egg problem. Does that make sense?

> I changed our codebase to use getXmlEncoding and all tests run green. So the general behaviour seems to be OK.

Right. Which suggests there is no bug? If there is, then we need to know what exactly you think it is.

**Comment by dirk-olmes** [comment]
Makes sense.

After your explanation of `getInputEncoding()` I have my doubts whether it is useful at all but that may only be me.

Thanks for your help.
