### ISSUE TITLE
My Mohist Minacraft 1.20.1 server crashes and it relases an Adoptium bug

### ISSUE THREAD

**Issue by AlexCraft855** [adoptium/adoptium-support#1187]
### Please provide a brief summary of the bug

Hi,
My server crashes because there is a bug with adoptium.
Crash report: https://paste.ee/p/vJEML
Thank you for read it,
Alex.

### Did you test with the latest update version?

- [x] Yes

### Expected Results

Server starts.

### Actual Results

When I try to start the server, it crashes.

### What Java Version are you using?

21.0.3+9

### How did you install Java?

With my hosting's Java install tool

### Did it work before?

```Shell
No.
```

### Did you test with other Java versions?

```Shell
Yes, java 17.
```

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are reporting that the game Minecraft crashed for you. Please try the following:

Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
often Minecraft crashes are caused by outdated graphics drivers
In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead
If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. MC-123456).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact our team to address the issue.
