### ISSUE TITLE
FTB Presents Direwolf20 1.21 A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by SLewellen97** [adoptium/adoptium-support#1192]
### Please provide a brief summary of the bug

When going to launch FTB Presents Direwolf20 1.21, I keep receiving "A fatal error has been detected by the Java Runtime Environment" as an error.
[hs_err_pid21008.log](https://github.com/user-attachments/files/17671821/hs_err_pid21008.log)

### Did you test with the latest update version?

- [X] Yes

### Expected Results

Expecting for the game to launch.

### Actual Results

An error continues to pop up with runtime errors.

### What Java Version are you using?

Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (21.0.5+11-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)

### What is your operating system and platform?

Windows 11 Pro

### How did you install Java?

MSI installer package

### Did it work before?

```Shell
The only thing that has changed since the last time I was able to open without crashing is the mod pack updating and me moving.
```

### Did you test with other Java versions?

```Shell
The Recommended Java Version that shows up when you install FTB.
Eclipse Adoptium -21.0.5 JDK (x64)
Oracle Corporation 1.8.0_431 JRE (x64)
```

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are reporting that the game Minecraft crashed for you. Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact our team to address the issue.
