### ISSUE TITLE
JVM crash when taking thread dump

### ISSUE THREAD

**Issue by alexsuter** [adoptium/adoptium-support#122]
A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007f20570e8559, pid=16013, tid=16026

JRE version: OpenJDK Runtime Environment (11.0.7+10) (build 11.0.7+10)
Java VM: OpenJDK 64-Bit Server VM (11.0.7+10, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)

Problematic frame:
C  [libpthread.so.0+0x12559]  pthread_getcpuclockid+0x9

[hs_err_pid16013.log](https://github.com/AdoptOpenJDK/openjdk-support/files/4736163/hs_err_pid16013.log)

**Comment by aahlenst** [comment]
What exactly did you do? There's at least half a dozen ways to produce a thread dump.

**Comment by alexsuter** [comment]
I have a hanging jvm application. When I take a threadump in VisualVM or with command line tool jstack the application is crashing. Is there anything what I can provide?

**Comment by karianna** [comment]
Can you provide a test case / reproduced?  Also, can you try an adoptopenjdk.net/upstream.html build?

**Comment by alexsuter** [comment]
**Reproduce**
I only can reproduce it with our product "Axon.ivy Designer", which is based on Eclipse. https://developer.axonivy.com/download
1. Need to start Axon.ivy Designer
2. Opening a Web Editor
3. Opening the Java Editor and working with "editor proposal" feature. 
After a while the JVM is hanging, which seems to be a deadlock with the Eclipse SWT environment and our own Web Editor which is based on JavaFX. Therefore I have created a bug report for eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=563990
I'm not sure this could also be a bug in the native code of eclipse swt. 

I think the deadlock is an issue in the Eclipse stack. Anyway, I think the JVM should never crash when taking thread dump, therefore I thought I think this is bug in the JVM itself? But if its a bug in native code of other components (eclipse swt) than the JVM could crash and this must be fixed in this component. Is this right?

**Upstream Build**
I can reproduce the problem with an upstream build.

**Comment by karianna** [comment]
> **Reproduce**
> I only can reproduce it with our product "Axon.ivy Designer", which is based on Eclipse. https://developer.axonivy.com/download
> 
> 1. Need to start Axon.ivy Designer
> 2. Opening a Web Editor
> 3. Opening the Java Editor and working with "editor proposal" feature.
>    After a while the JVM is hanging, which seems to be a deadlock with the Eclipse SWT environment and our own Web Editor which is based on JavaFX. Therefore I have created a bug report for eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=563990
>    I'm not sure this could also be a bug in the native code of eclipse swt.
> 
> I think the deadlock is an issue in the Eclipse stack. Anyway, I think the JVM should never crash when taking thread dump, therefore I thought I think this is bug in the JVM itself? But if its a bug in native code of other components (eclipse swt) than the JVM could crash and this must be fixed in this component. Is this right?
> 
> **Upstream Build**
> I can reproduce the problem with an upstream build.

Yeah, this is almost certainly an underlying Eclipse issue.  We'll close this, for now, bu the Eclipse folks can reopen it if need be.

**Comment by iloveeclipse** [comment]
Regarding the crash: see https://bugzilla.redhat.com/show_bug.cgi?id=1832121. The native stack looks same.

Once we restore our RH account rights (lost in transition from one company to another) we will ask RH account guys to drive investigation, especially now we have here a better reproducer.

I think this is JVM bug unless the opposite is proven :-).

**Comment by iloveeclipse** [comment]
I'm trying to follow steps, but I fail at point 3 below: I have no idea about how to open Web Editor (I assume I have to create a project, but again, I have no idea how to proceed with that).

Please could you update Axon specific steps, so that every one can reproduce it?

My steps 

1) Download https://developer.axonivy.com/download. For Linux 

$ cd /tmp
$ wget "https://download.axonivy.com/8.0.6/AxonIvyDesigner8.0.6.2005291209_Linux_x64.zip"
$ unzip /tmp/AxonIvyDesigner8.0.6.2005291209_Linux_x64.zip 

2) Run the designer, select /tmp/workspace as workspace
$ ./Axon.ivy\ Designer
3) Open a Web Editor // FROM HERE ON I'm lost
4) Open the Java Editor and work with "editor proposal" feature. After a while the JVM is hanging, which seems to be a deadlock with the Eclipse SWT environment and Web Editor which is based on JavaFX.
5) Try to create JVM thread dump via jstack.

**Comment by alexsuter** [comment]
Hello @iloveeclipse 
Thanks for investigation! 

The following GIF shows how you can reproduce the problem:
![hangin-axonivy-designer](https://user-images.githubusercontent.com/7498380/84081298-fca8aa00-a9dd-11ea-8a85-1aabc0107c64.gif)

I can pretty good reproduce the problem on my system (Ubuntu 20.04). After the web editor was open you may need to search different types in the Java Editor. The Java Editor shows up the proposal itself and next to the proposals there is a further window which shows the Javadoc. I assume that this window is based on webkit, because JavaDoc is pseudo-html and will be rendered in a "browser-like window". And it seems to be that while disposing this window the issue occurs.

**Comment by aahlenst** [comment]
@karianna You've reopened this one. Have you reached the conclusion that this isn't an Eclipse issue?

**Comment by karianna** [comment]
@alexsuter Can you re-run this with Jacoco removed?  Also, can you try our nightly 11.0.8?

**Comment by alexsuter** [comment]
I'm currently on holiday. I will give you feedback next week!

**Comment by alexsuter** [comment]
@karianna 
- I could not find any Jacoco libraries in the product. Did you find something?
- Tried with 11.0.8 nightly. Error still exists.

**Comment by karianna** [comment]
I got my wires crossed on Jacoco sorry!

**Comment by aahlenst** [comment]
The crash dump indicates that the problem of the crashing JVM might be in the JVM. That the JVM hangs is likely a problem of Eclipse or Axon Ivy. We can only offer some help with the JVM crash.

@alexsuter Options that you have:

* Wait for Red Hat to figure it out. Considering that the stack trace in https://bugzilla.redhat.com/show_bug.cgi?id=1832121 matches, I think this is the best option because that way the fix will end up in OpenJDK.
* Report it to Oracle via https://bugreport.java.com/bugreport/. Before you do that, you have to test with a download from https://www.oracle.com/java/technologies/javase-downloads.html. If the problem happens with 15 or newer, the fix should end up in OpenJDK. If it only affects 11.0.8, the fix might only end up in Oracle's version.
* Test with https://adoptopenjdk.net/upstream.html?variant=openjdk11&ga=ea. If the problem persists, report back. We have the to find someone who can report it to OpenJDK.

**Comment by alexsuter** [comment]
@aahlenst I will choose option one and try to get in touch with Read Hat.

**Comment by iloveeclipse** [comment]
While the JVM bug is still there and not fixed (https://bugzilla.redhat.com/show_bug.cgi?id=1897150), Eclipse specific crashes should be fixed now with 4.19, see bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=569853.

**Comment by karianna** [comment]
This was marked as a won't fix for Java 11 upstream (it is resolved in 17).  Clients will need to use the API calls in the correct order
