### ISSUE TITLE
JDK 17 with Eclipse 2021-09: WindowBuilder Design page blank

### ISSUE THREAD

**Issue by HREferg** [adoptium/adoptium-support#370]
JDK 17.0.0.35 (Windows x64 version)

## Summary
JDK 17 with Eclipse 2021-09: WindowBuilder Design page blank

## Steps to reproduce
Any Java code window using WindowBuilder fails to show anything on the Design page.
This is the same bug as Eclipse had with JDK 16, but there was a workaround for 16 in that you could add the line 
--illegal-access=permit 
to the eclipse.ini file to fix the problem. This no longer works with JDK17. 
Also fails with this entry removed.

## Expected results
As above

## Actual results
As above

## Triaging info
Paste the entire output of java -version.
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

What is your operating system and platform?
Windows 10 21H1 19043.1237 on x86-64

How did you install Java?
msi installer

Did it work before?
See above re JDK 16

Did you test with other Java versions?
Worked before (plus eclipse.ini fix) with:
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

**Comment by BrijeshNekkare** [comment]
Unlikely a JDK bug, please refer [JEP 403: Strongly Encapsulate JDK Internals](https://openjdk.java.net/jeps/403)

Key parts of JEP 403 being:

> 1. --illegal-access=permit - Default mode from JDK 9 through JDK 15
> 2. -illegal-access=deny - Default mode in JDK 16, which you have overcome by usage of --illegal-access=permit
> 3. JDK-17 - No longer be possible for end users to use the --illegal-access option to enable access to internal elements of the JDK. It will still be possible to use the --add-opens command-line option, or the Add-Opens JAR-file manifest attribute, to open specific packages.
> 

What warning message[s] pop up when you are running your application.

**Comment by HREferg** [comment]
There are no warning messages I’ve seen – just a blank Eclipse screen.

Normally, when switching to WB Design, there is a popup noting the Design page is opening – this does not appear.

 

From what you say it appears this is a WB error? And they need to conform to the JEP403 restrictions?

So I need to log a WB bug?

Or can I still do a workaround by use of –add-opens? In which case what should that look like in full?

**Comment by BrijeshNekkare** [comment]
From a long term perspective its recommended to stop access to internal elements of the JDK, so you should certainly seek support of your application team to migrate to JDK17. 

List of the packages affected is available [here](https://cr.openjdk.java.net/~mr/jigsaw/jdk8-packages-strongly-encapsulated). The sun.misc and sun.reflect packages will still be exported by the jdk.unsupported module, and will still be open so that code can access their non-public elements via reflection. No other JDK packages will be open in this way.

The java option **--add-opens $module/$package=$reflectingmodule** can be used to open $package of $module for deep reflection to $reflectingmodule. Code in $reflectingmodule can hence reflectively access all types and members in $package but other modules can not. When setting $reflectingmodule to ALL-UNNAMED, all code from the class path can reflectively access that package.

Example:

> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make ClassLoader.defineClass accessible: module java.base does not "opens java.lang" to unnamed module


Workaround using add-opens:

> --add-opens java.base/java.lang=ALL-UNNAMED

Reference: [add-opens](https://nipafx.dev/five-command-line-options-hack-java-module-system/#reflectively-accessing-internal-apis-with---add-opens)

**Comment by HREferg** [comment]
Have done some digging around and it looks like the WindowBuilder team are aware of this and intend to fix in v1.9.8 (due Oct 9).
On that basis this should be closed as not a JDK 17 bug.
