### ISSUE TITLE
1.5.0 stone block3 err

### ISSUE THREAD

**Issue by wnsgml0814** [adoptium/adoptium-support#692]
### Please provide a brief summary of the bug

[hs_err_pid13588.log](https://github.com/adoptium/adoptium-support/files/10434454/hs_err_pid13588.log)
plye map and crash

### Expected Results

crash

### Actual Results

crash

### What Java Version are you using?

1.8.0_351-b10

**Comment by karianna** [comment]
Can you try our latest 17.0.5 and post the log if it still happens?

**Comment by karianna** [comment]
@wnsgml0814 ^^

**Comment by Daimoh19** [comment]
> ### Please provide a brief summary of the bug
> [hs_err_pid13588.log](https://github.com/adoptium/adoptium-support/files/10434454/hs_err_pid13588.log) plye map and crash
> 
> ### Please provide steps to reproduce where possible
> _No response_
> 
> ### Expected Results
> crash
> 
> ### Actual Results
> crash
> 
> ### What Java Version are you using?
> 1.8.0_351-b10
> 
> ### What is your operating system and platform?
> _No response_
> 
> ### How did you install Java?
> _No response_
> 
> ### Did it work before?
> _No response_
> 
> ### Did you test with other Java versions?
> _No response_
> 
> ### Relevant log output
> _No response_

Hi, sorry for my English (I use google translator...) The fact is that I also have this problem. More specific is version 1.5.0 of stoneblock, 1.4.3 is luxurious. This mass because of the driver version... unfortunately I can only make it work (it's AMD) with 22.6.1 backwards. The following versions causes minecraft to crash (this modpack).

**Comment by karianna** [comment]
This need to be reported to the Mod author.
