### ISSUE TITLE
Cannot download testimage of 19 GA

### ISSUE THREAD

**Issue by toshiona** [adoptium/adoptium-support#699]
### Please provide a brief summary of the bug

I cannot download testimage of 19ga. I could download the ones of 11(ea/ga), 17(ea/ga), and 19ea.
https://api.adoptium.net/v3/binary/latest/19/ga/linux/x64/testimage/hotspot/normal/adoptium?project=jdk

### Expected Results

Download the testimage file

### Actual Results

No file was found

### What Java Version are you using?

N/A

**Comment by zdtsw** [comment]
seems like testimage was not uploaded not only for 19 but all other versions too.

the GA one on 17,11 that you could download are not the ones from latest GA release, could not even see in the last 2/3 GA we have testimage uploaded for 11,17
in this case it makes sense why no 19GA at all.

**Comment by steelhead31** [comment]
The GA image for JDK17, is from 09/2021, and is very old... Adoptium do not ship testimages for the ga release of any of the JDKs, they are available from the nightly builds only.

**Comment by smlambert** [comment]
We should in fact rethink this and likely start shipping the GA testimage, since it is used for a subset of native tests in the openjdk group in the AQAvit suite.  (The implication being that if I ran a test with SDK_RESOURCE=releases, which would go fetch the latest GA release, there would be no matching testimage to use for it, and the nearest nightly image has no guarantee of being in sync with the GA binary).

**Comment by steelhead31** [comment]
The test images for the GA releases of JDKs 11,17 & 19 are now available. ( jdk-11.0.18+10, jdk-17.0.6+10 & jdk-19.0.2+7 )

**Comment by smlambert** [comment]
thanks @steelhead31 !

**Comment by toshiona** [comment]
Thanks! It works.
