### ISSUE TITLE
STM32cube ide

### ISSUE THREAD

**Issue by mahdiqnb** [adoptium/adoptium-support#798]
## Question

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
SWT WebKitGDBus: error creating DBus server Error binding to address (GUnixSocketAddress): No such file or directory
SWT WebKit: error initializing DBus server, dBusServer == 0

(STM32CubeIDE:60613): GLib-GIO-CRITICAL **: 12:06:34.515: g_dbus_server_get_client_address: assertion 'G_IS_DBUS_SERVER (server)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f4b0503ed16, pid=60613, tid=60614
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.17+8 (11.0.17+8) (build 11.0.17+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (11.0.17+8, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libswt-gtk-4950r5.so+0x3ed16]  Java_org_eclipse_swt_internal_C_strlen+0xf
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid60613.log
Compiled method (nm)    8250 5626     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f4ba3d8d790,0x00007f4ba3d8db30] = 928
 relocation     [0x00007f4ba3d8d908,0x00007f4ba3d8d938] = 48
 main code      [0x00007f4ba3d8d940,0x00007f4ba3d8db28] = 488
 oops           [0x00007f4ba3d8db28,0x00007f4ba3d8db30] = 8
Compiled method (nm)    8257 5626     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f4ba3d8d790,0x00007f4ba3d8db30] = 928
 relocation     [0x00007f4ba3d8d908,0x00007f4ba3d8d938] = 48
 main code      [0x00007f4ba3d8d940,0x00007f4ba3d8db28] = 488
 oops           [0x00007f4ba3d8db28,0x00007f4ba3d8db30] = 8
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
                                                                                                      

Java version:11

Your operating system and platform:kali linux on Amd64

**Comment by SimeonPr** [comment]
I am having similar issues with Eclipse Capella MBSE.
When starting Capella and opening a diagram, I get the same error.
I am not sure which information is needed to debug this, so if you need any more information, let me know.

I am on Linux:
`uname -a`
`Linux laptop 6.3.1-arch2-1 #1 SMP PREEMPT_DYNAMIC Wed, 10 May 2023 08:54:47 +0000 x86_64 GNU/Linux`

# Here is the core dump when running Capella:
[hs_err_pid21815.log](https://github.com/adoptium/adoptium-support/files/11477315/hs_err_pid21815.log)

# People have been experiencing similar issues with different programs:

https://forum.mbse-capella.org/t/error-running-capella-under-linux-ubuntu-23-04/6328/2
https://community.st.com/s/question/0D53W00002ByOp1SAF/error-trying-to-launch-stm32cubeide-on-linux
https://forum.garudalinux.org/t/talend-eclipse-based-app-libswt-gtk-problem-since-last-pacman-system-update/27200/11

# Here is the terminal output:
Sorry for poor formatting.

WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.eclipse.osgi.internal.framework.SystemBundleActivator (file:/home/simeon/capella/plugins/org.eclipse.osgi_3.16.300.v20210525-1715.jar)
WARNING: Please consider reporting this to the maintainers of org.eclipse.osgi.internal.framework.SystemBundleActivator
WARNING: System::setSecurityManager will be removed in a future release
SWT WebKitGDBus: error creating DBus server Error binding to address (GUnixSocketAddress): No such file or directory
SWT WebKit: error initializing DBus server, dBusServer == 0


(Capella:20241): GLib-GIO-CRITICAL **: 13:21:55.347: g_dbus_server_get_client_address: assertion 'G_IS_DBUS_SERVER (server)' failed


 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f2b6e23eb86, pid=20241, tid=20242

 JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)
 Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, sharing, tiered, compressed oops, ompressed class ptrs, g1 gc, linux-amd64)
 Problematic frame:
 C  [libswt-gtk-4944r26.so+0x3eb86]  Java_org_eclipse_swt_internal_C_strlen+0xf

 An error report file with more information is saved as:
 /home/simeon/capella/hs_err_pid20241.log
Compiled method (n/a)   47631 4937     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f2bd8fc1190,0x00007f2bd8fc1500] = 880
 relocation     [0x00007f2bd8fc12f0,0x00007f2bd8fc1320] = 48
 main code      [0x00007f2bd8fc1320,0x00007f2bd8fc14f8] = 472
 oops           [0x00007f2bd8fc14f8,0x00007f2bd8fc1500] = 8
Compiled method (n/a)   47631 4937     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f2bd8fc1190,0x00007f2bd8fc1500] = 880
 relocation     [0x00007f2bd8fc12f0,0x00007f2bd8fc1320] = 48
 main code      [0x00007f2bd8fc1320,0x00007f2bd8fc14f8] = 472
 oops           [0x00007f2bd8fc14f8,0x00007f2bd8fc1500] = 8
Compiled method (n/a)   47638 4937     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f2bd8fc1190,0x00007f2bd8fc1500] = 880
 relocation     [0x00007f2bd8fc12f0,0x00007f2bd8fc1320] = 48
 main code      [0x00007f2bd8fc1320,0x00007f2bd8fc14f8] = 472
 oops           [0x00007f2bd8fc14f8,0x00007f2bd8fc1500] = 8

**Comment by Breezeman69** [comment]
I am having the same issue with Talend Open Studio that uses Eclipse.  I am running:

uname -a
Linux fedora38 6.2.15-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May 11 17:37:39 UTC 2023 x86_64 GNU/Linux

This issue came about right after I upgraded my sysem from Fedora 37 to Fedora 38 and has been broken ever since.  I see there was a new version of Java OpenJDK v 17.07.0.7-4 however  the error in the core dump is the same,  see below.
Please help in resolution to this issue.

Here is the Core Dump
[hs_err_pid3833.log](https://github.com/adoptium/adoptium-support/files/11507828/hs_err_pid3833.log)

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc7a3a3eb86, pid=3833, tid=3834
#
# JRE version: OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-4.fc38) (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-4.fc38) (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libswt-gtk-4944r26.so+0x3eb86]  Java_org_eclipse_swt_internal_C_strlen+0xf
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/stephenmauersberg/core.3833)
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-17-openjdk-portable&version=38
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Xms512m -Xmx1536m -Dfile.encoding=UTF-8 -Dosgi.requiredJavaVersion=11 -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=512m --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-modules=ALL-SYSTEM /home/stephenmauersberg/Apps/TOS_DI-20211109_1610-V8.0.1/plugins/org.eclipse.equinox.launcher_1.6.200.v20210416-2027.jar -os linux -ws gtk -arch x86_64 -showsplash -launcher /home/stephenmauersberg/Apps/TOS_DI-20211109_1610-V8.0.1/TOS_DI-linux-gtk-x86_64 -name TOS_DI-linux-gtk-x86_64 --launcher.library /home/stephenmauersberg/Apps/TOS_DI-20211109_1610-V8.0.1/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.200.v20210429-1609/eclipse_11401.so -startup /home/stephenmauersberg/Apps/TOS_DI-20211109_1610-V8.0.1/plugins/org.eclipse.equinox.launcher_1.6.200.v20210416-2027.jar --launcher.overrideVmargs -exitdata 18 -vm /usr/bin/java -vmargs -Xms512m -Xmx1536m -Dfile.encoding=UTF-8 -Dosgi.requiredJavaVersion=11 -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=512m --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-modules=ALL-SYSTEM -jar /home/stephenmauersberg/Apps/TOS_DI-20211109_1610-V8.0.1/plugins/org.eclipse.equinox.launcher_1.6.200.v20210416-2027.jar

**Comment by karianna** [comment]
@SimeonPr - please do upgrade to 17.0.7 and update the GTK drivers / version to the latest but assuming neither of those work you'll need to report this to the Eclipse Capella MBSE folks.  I suspect this is a SWT bug that needs fixing.

@Breezeman69 You're using Red Hat's distribution (although I suspect Eclipse Temurin would also fail here). Please try updating the GTK drivers / version to the latest but assuming neither of those work you'll need to report this to the Eclipse Talend and Red Hat folks

**Comment by Breezeman69** [comment]
I checked and looks like I have that latest version installed currently. 
Package gtk3-3.24.37-1.fc38.x86_64 is already installed.
Package gtk3-3.24.37-1.fc38.i686 is already installed.

I might note that I spun up a fresh VM of Fedora 38 and Isntalled Talend Open Studio and did n ot experience this issue.  It' slike something got orphaned or replaced when did the upgrade from Fedor 37 to 38 on my primary OS.  I found this topic dicussed on several different forums and discussion threads but no viable solution to address it at this point.  Iamhoping that will change at  some point since a full system rebuild right now is out of the question give the time and effort that would be required here.

Thanks

**Comment by gkobeaga** [comment]
This [answer](https://community.st.com/s/question/0D53W00002FDNNJSA5/can-no-longer-create-a-new-workspace-stm32cubeide-1121) on the ST community forum worked for me (credits to [Marcelo Jimenez](https://community.st.com/s/profile/0053W000001piMkQAI)): 

1. Create the file `fix_stm32cubeide.sh` and include the following lines:
```bash
#! /bin/bash
#
# Fixes the STM32CubeIDE crash bug when creating a new workspace.
#
# Does not happen to everyone, but if you are the unlucky guy, you can try
# this script.
#

if [[ "$#" -ne 1 ]]; then
    echo "Usage: $0 <workspace directory name>"
    exit 1
fi

printf "\nFixing \'%s\'.\n" "$1"
read -p "Continue? [y/*] " -n 1 -r
#echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo
    echo Aborting
    exit 1
fi
echo

WORKSPACE=$1
FIX_BASE=${WORKSPACE}/.metadata/.plugins
INFORMATIONCENTER=${FIX_BASE}/com.st.stm32cube.ide.mcu.informationcenter
CORE=${FIX_BASE}/org.eclipse.cdt.core
touch "${INFORMATIONCENTER}"/2.1.0.202202250925
touch "${INFORMATIONCENTER}"/2.1.1.202206161110
touch "${INFORMATIONCENTER}"/2.1.500.202211100823
touch "${INFORMATIONCENTER}"/2.1.700.202302091318
echo "*** SESSION May 09, 2023 20:48:57.537 ------------------------------------------" >"${CORE}"/.log

echo Done!

```
2. Execute `./fix_stm32cubeide.sh ~/STM32CubeIDE/\<WORKSPACE\>`
3. Execute STM32CubeIDE and try to open the ~/STM32CubeIDE/\<WORKSPACE\> workspace. This time it will crash.
4. Execute STM32CubeIDE again and try to open the ~/STM32CubeIDE/\<WORKSPACE\> workspace. This time it should not crash.

**Comment by Breezeman69** [comment]
This fix seems to be specific to the STM32cube ide.  Is there a similar script to fix Talend's Open Studio?

**Comment by karianna** [comment]
It'll almost certainly be the same fix judging by the error message.

**Comment by TheWeirdDev** [comment]
Follow this comment. It should fix the issue: https://github.com/adoptium/adoptium-support/issues/785#issuecomment-1585740194
