### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) 

### ISSUE THREAD

**Issue by AronneDellOca** [adoptium/adoptium-support#809]
### Please provide a brief summary of the bug

I am running a COMSOL 6.1 case and it crashes giving the following error, could somebody help me with that?
Many thanks
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffacf4d5c98, pid=7160, tid=36708
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.13+8 (11.0.13+8) (build 11.0.13+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (11.0.13+8, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00007ffacf4d5c98
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#

### Expected Results

to end the simulation

### Actual Results

the simulation crashes

### What Java Version are you using?

version 8

### What is your operating system and platform?

windows 10 Pro - Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz, 3696 Mhz, 10 core, 20 

### Did you test with the latest update version?

```Shell
yes
```

**Comment by ThatFatMan42** [comment]
I'm going to piggyback on this because I'm running into the same/similar error

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffde3afe0e6, pid=6932, tid=3260
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x30e0e6]

In my instance it happens in the FTB launcher for any version of a minecraft modpack I install (FTB One 1.19 v2.7 and v2.6, Direwolf20 pack for 1.19).  

I have installed and reinstalled the latest version of Java and updated my video card drivers.  Running windows 11, intel 6700k processor, 16GB ram.  It's a fairly new install but everything is up to date as far as I can tell.
[hs_err_pid6932.log](https://github.com/adoptium/adoptium-support/files/11645982/hs_err_pid6932.log)

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are reporting that the game Minecraft crashed for you. Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact our team to address the issue.

**Comment by karianna** [comment]
https://minecraft.fandom.com/wiki/Tutorials/Update_Java
