### ISSUE TITLE
java bug 

### ISSUE THREAD

**Issue by TymekSL** [adoptium/adoptium-support#820]
### Please provide a brief summary of the bug

This is the bug when I trying turn on the server and join it. I have connection reset and server is restarting with this bug 

### Please provide steps to reproduce where possible

Turning on the server (?)

### Expected Results

Turn on the server

### Actual Results

Server is restarting

### What Java Version are you using?

17.0.7

### What is your operating system and platform?

Ubuntu 22.04 

### How did you install Java?

zip

### Did it work before?

```Shell
Yes
```

### Did you test with the latest update version?

```Shell
Yes
```

### Did you test with other Java versions?

```Shell
No
```

### Relevant log output

```Shell
>#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f74c23bff74, pid=1, tid=200
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x97f74]  pthread_mutex_lock+0x4
#
# Core dump will be written. Default location: /home/container/core.1
#
# An error report file with more information is saved as:
# /home/container/hs_err_pid1.log
20:31:06 [WARNING] Event PostLoginEvent(player=Leo693) took 117ms to process!
20:31:06 [INFO] [Leo693] <-> ServerConnector [Auth-1] has connected
>#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007f74c2350898]
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
```

**Comment by karianna** [comment]
@TymekSL Is this a minecraft server?

**Comment by coderFlameyosFlow** [comment]
@karianna I also got this on my minecraft server.

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are reporting that the game Minecraft crashed for you. Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact our team to address the issue.
