### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) 

### ISSUE THREAD

**Issue by soelie22** [adoptium/adoptium-support#908]
### Please provide a brief summary of the bug

I launch any modpack, it proceeds to load and right before launching it gives me the error this happens with any modpack
# EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8e8926280, pid=18804, tid=32180
# A fatal error has been detected by the Java Runtime Environment:

### Please provide steps to reproduce where possible

I have no idea how this happened

### Expected Results

.

### Actual Results

.

### What Java Version are you using?

version 8 update 381

### What is your operating system and platform?

windows 11 home, version 10.0.22621, x64-based

### How did you install Java?

java.com

### Did it work before?

```Shell
i dont know if the java version is the issue, but the app used to work for me like 2-3 weeks ago
```

### Did you test with the latest update version?

```Shell
yes i tried updating java but it was allready updated
```

### Did you test with other Java versions?

```Shell
yes i just tried launching it with this java: Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)

but that didnt work either
```

### Relevant log output

```Shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8e8926280, pid=49404, tid=17116
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [atio6axx.dll+0x196280]
```

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are reporting that the game Minecraft crashed for you. Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact our team to address the issue.
