### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by Isaacyona** [adoptium/adoptium-support#967]
### Please provide a brief summary of the bug

Feather loaded up perfectly but now its crashing when i join a server

### Please provide steps to reproduce where possible

Get feather
Load up 1.20.1 
get into main menu
try to join server
crashed

### Expected Results

 client

### Actual Results

crashed

### What Java Version are you using?

17.0.3+7

### What is your operating system and platform?

windows 11

### How did you install Java?

through the website

### Did it work before?

```Shell
Lunar client worked but now both lunar and feather dont
```

### Did you test with the latest update version?

```Shell
no
```

### Did you test with other Java versions?

```Shell
no
```

### Relevant log output

```Shell
A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffd92f22fb0, pid=12772, tid=9824
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.3+7 (17.0.3+7) (build 17.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (17.0.3+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [ig7icd64.dll+0x452fb0]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
info: # An error report file with more information is saved as:
# feather/java_error.log
info: #
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
info: [2023-12-04T01:24:49Z ERROR rust_launcher::messaging::channel] error during messaging worker: An existing connection was forcibly closed by the remote host. (os error 10054)
info: [2023-12-04T01:24:50Z INFO  rust_launcher::start::bindings] launch stalled
```

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are reporting that the game Minecraft crashed for you. Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact our team to address the issue.
