### ISSUE TITLE
Support for SUSE Linux Enterprise Server 15

### ISSUE THREAD

**Issue by philippecade** [adoptium/adoptium-support#990]
## Question

Is SUSE Linux Enterprise Server 15 a supported OS for Adoptium?

## Context

Java version: 17 and 21

On the list of supported platforms [1], SUSE Linux Enterprise Server (SLES) 12 is listed for the Linux (x64) architecture but not SUSE Linux Enterprise Server (SLES) 15.

At the same time, this blog post mentions that RPM packages are available for SUSE 12 and 15: [2]

We are mainly interested in the Linux x64 architecture but I guess the question is also valid for other achitectures.

[1] https://adoptium.net/supported-platforms/
[2] https://adoptium.net/es/blog/2021/12/eclipse-temurin-linux-installers-available/

(internal reference 366643)

**Comment by jerboaa** [comment]
https://adoptium.net/supported-platforms/#_footnotedef_1 states why SLES 12 is being mentioned:

```
These builds should work on any distribution with glibc version 2.17 or higher. Versions up to 17 will work with glibc 2.12 
```

**Comment by jerboaa** [comment]
Adding PMC agenda as we should perhaps clarify that (and if so, how).

**Comment by sxa** [comment]
Thanks Philippe SLES15 should be considered supported either through the package install using the commands in the blog post you reference, or by downloading the appropriate Linux tarball from the main download site. If you find any issues with it please let us know. We don't have quite so many SuSE systems as other distributions due to limited capacity but we do some testing on it.

I'm going to keep this issue open pending doing some docoumentation updates around this:
- [ ] Update the supported platforms page
- [ ] Look at adding SLES15SP5 support into the artifactory repository (Currently only explicitly lists [up to 15.4](https://packages.adoptium.net/ui/native/rpm/opensuse), but they all contain the same data)

Related: https://github.com/adoptium/infrastructure/issues/3135 to perform increased testing in SLES BCI images.

**Comment by philippecade** [comment]
Thanks for the quick feedback, I will transmit your answer to our customer and ask them to report any issues.

**Comment by sxa** [comment]
Closing this as the two action items above have been completed:
- https://github.com/adoptium/adoptium.net/pull/2576
- https://github.com/adoptium/installer/pull/793
